openapi: '3.0.1'
info:
  version: '0.1.2'
  title: 'DLT Booth API'
  description: This document specifies the REST API for the DLT Booth service.
externalDocs:
  description: Github 
  url: https://github.com/Sedimark/dlt-booth
servers:
- url: http://localhost:1234
tags:
- name: Delegated
  description: Identity operations managed directly by the DLT Booth.
- name: DIDs
- name: Other
paths:

################################################################
#                                                              #
#                          Identites                           #
#                                                              #
################################################################

  /delegated/identities:
    post:
      summary: Creates a user identity.
      description: In detail, it creates a new Did embedding in the document an identity public key and an ethereum address securely stored in the booth. Finally reaches the Issuer in order to receive a Verifiable Credential that contains the claims provided in the request body. 
      tags:
      - Delegated
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Identity'
      responses: 
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialJwt'  
        403:
          description:  The operation should not be executed again without deleting an existing identity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Operation aborted due to an unexpected error during execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Delegated
      summary: Delete user identity
      description: In detail, the Booth requests to the issuer to revoke the Verifiable Credential. Finally, the identity stored in the Booth is deleted.
      responses:
        200: 
          description: Deleted
        404:
          description:  Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Operation aborted due to an unexpected error during execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - Delegated
      summary: Get identity
      responses:
        200:
          description: Get credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialJwt'  
        404:
          description:  Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Operation aborted due to an unexpected error during execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      description: If the booth is registered, it returns the JWT payload enveloping a Verifiable Credential
  /dids/{did}:
    parameters:
      - in: path
        name: did
        required: true
        schema:
          type: string
    get:
      summary: Resolve a DID on the configured verifiable data registry
      description: Given a DID as an input, it queries the configured node as a client to retrieve the current state of the DID Document
      responses:
        200:
          description: Resolved
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/DidDocument'
        500:
          description: Unexpected error
################################################################
#                                                              #
#                          Offerings                           #
#                                                              #
################################################################
  /delegated/offerings:
    post:
      summary: DLT-Booth creates a new offering
      description: Generate a new offering on the configured Factory SC using the identity of the DLT-Booth
      tags:
        - Delegated
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Offering'
                - $ref: '#/components/schemas/OfferingConfig'
      responses:
        201:
          description: NFT created
          content:
            application/json:
              schema:
                type: object
                properties:
                  nftAddress:
                    type: string
              example:
                nftAddress: '0x1a5FdBc891c5D4E6aD68064Ae45D43146D4F9f3a'
        500:
          description: Internal Error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Retrieve the list of available offerings
      description: Reads from the Factory SC and returns the list of addresses of minted NFTs
      tags:
        - Delegated
      responses:
        200:
          description: "List found: the list of available addresses is returned"
          content:
            application/json:
              schema:
                type: object
                properties:
                  addresses:
                    type: array
                    items:
                      type: string
                      example: '0x1a5FdBc891c5D4E6aD68064Ae45D43146D4F9f3a'
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                  
  /offering/{address}:
    parameters:
    - in: path
      name: address
      required: true
      schema:
        type: string
    get:
      summary: Get NFT's offering details, given the NFT address
      description: Returns the details that a specific offering SC can return
      responses:
        200:
          description: Details of the NFT with the provided address
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties: 
                      owner: 
                        type: string
                    example:
                      owner: '0x1a5FdBc891c5D4E6aD68064Ae45D43146D4F9f3a'
                  - $ref: '#/components/schemas/Offering'
        500:
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
################################################################
#                                                              #
#                          COMPONENTS                          #
#                                                              #
################################################################

components:
  schemas:
    CredentialJwt:
      type: object
      example: 
       exp: 1775049930
       iss: did:iota:lnk:0x9f42fd4d8712613760030e0ae3bc53decc39b4c889b1ea8db2b1aa007d734893
       nbf: 1743427530
       jti: http://sedimark-issuer:3213/api/credentials/6
       sub: did:iota:lnk:0x73ec91fcd41f30836169f2a7b89166b6ba0093209a03d236e96e79c5e63cb230
       vc:
         '@context':
           - https://www.w3.org/2018/credentials/v1
           - schema: http://schema.org/
         type:
           - VerifiableCredential
           - MarketplaceCredential
         credentialSubject:
           schema:alternateName: someUsername
           schema:memberOf: SEDIMARK marketplace
                   
    Credential:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
    Service:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        serviceEndpoint: 
         type: string  
    Identity:
      type: object
      properties: 
        credential: 
          $ref: '#/components/schemas/Credential'
        services:
          type: array
          items: 
            $ref: '#/components/schemas/Service'
      required:
        - credential
    DidDocument:
      type: object
      example:
        doc:
          id: did:iota:lnk:0x94e4a3c83a66c2592069e74937887f9f2baf63d96f156d36dabd3f3482395324
          verificationMethod:
            - id: did:iota:lnk:0x94e4a3c83a66c2592069e74937887f9f2baf63d96f156d36dabd3f3482395324#m0K_TnUAenJRKuJ_WU8prsHavPcsACNdRRxk3vPl8Mg
              controller: did:iota:lnk:0x94e4a3c83a66c2592069e74937887f9f2baf63d96f156d36dabd3f3482395324
              type: JsonWebKey2020
              publicKeyJwk:
                kty: OKP
                alg: EdDSA
                kid: m0K_TnUAenJRKuJ_WU8prsHavPcsACNdRRxk3vPl8Mg
                crv: Ed25519
                x: Fl_ytZJjvo6mDXhydn-ah-RLcyWXX1mVJRKKGlJ21Ds
          meta:
            created: '2025-02-17T10:37:29Z'
            updated: '2025-02-17T10:37:29Z'
            governorAddress: lnk1qqg0e766887n74jj70mgagmgkvvdzwk9f6mz9m67gje249e683wlslhqw98
            stateControllerAddress: lnk1qqg0e766887n74jj70mgagmgkvvdzwk9f6mz9m67gje249e683wlslhqw98
    
    Offering:
      type: object
      properties:
        name: 
          type: string
        descriptionUri:
          type: string
        descriptionHash: 
          type: string
      example:
        name: OfferingName
        descriptionUri: http://example.com
        descriptionHash: b133a0c0e9bee3be20163d2ad31d6248db292aa6dcb1ee087a2aa50e0fc75ae2
        
    OfferingConfig:
      type: object
      properties:
        symbol:
          type: string
        dtName:
          type: string
        dtSymbol: 
          type: string
        maxSupply: 
          type: integer
      example: 
        symbol: "NFT"
        dtName: "AGREEMENT"
        dtSymbol: "AGREE"
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string